name: docker-compose-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'c*'

permissions:
    contents: write
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # - run: |
      #     sudo chown -R runner:docker ./

    # sudo chown :1000 testdir/
    # sudo chmod g+s testdir/
    # continue-on-error: true
      - name: set permission and run
        run: |
          sudo chmod -R +x . && \
          ./build.sh
          
      # - uses: fastai/workflows/ssh@master
      #   with:
      #     ssh_key: ${{ secrets.SSH_KEY }}
      #     key_file: id_ecdsa
          
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@master
      
      # - working-directory: u-boot-imx6
      #   run: |
      #     mkdir dist && \
      #     mv _SPL ./dist/SPL && \
      #     mv 123.txt ./dist

      # - name: Archive Release
      #   uses: thedoctor0/zip-release@master
      #   with:
      #     type: 'zip'
      #     directory: "u-boot-imx6/dist"
      #     filename: "u-boot-imx6-${{ github.ref_name }}.zip"
        
      # - name: Release prebuilt
      #   uses: ncipollo/release-action@v1
      #   with:
      #     artifacts: "u-boot-imx6/dist/u-boot-imx6-${{ github.ref_name }}.zip"
      #     allowUpdates: true
      #     token: ${{ secrets.GITHUB_TOKEN }}
